### ISSUE TITLE
Getting [object Object] when sending formatted messages

### ISSUE THREAD

**Issue by danielechalar** [markstory/hubot-xmpp#114]
I have tried following : https://api.slack.com/docs/message-attachments

But I always receive: http://prnt.sc/d8h1e8 as response

I'm using `msg.send messageWithAttachments` but not working.

Also, I tried alternatives found here https://github.com/slackapi/hubot-slack/issues/170
and I always get [object Object] as result in Slack

simple messages works great

Any idea? thank you in advanced

**Comment by markstory** [comment]
Are you sure that you have the right repository? This is a hubot adapter for XMPP not Slack.
