### ISSUE TITLE
hubot does not appear in more than one MultiUserChannel

### ISSUE THREAD

**Issue by saljut7** [markstory/hubot-xmpp#115]
Hi,

I've set up hubot with Prosody 0.10 on Debian8. CLI communication works, direct XMPP conversaiton with MyBot aswell and MyBot appears in a hubt-test MUC I've set up (where communication works as well).

No I killed MyBot and tried to add another (regular) MUC via:

```
export HUBOT_XMPP_ROOMS=hubot-test@conference.MyXMPPServer.tld,MyMUC@conference.MyXMPPServer.tld
```

Problem: MyBot still only appears in `hubot-test@conference.MyXMPPServer.tld` but not in `MyMUC@conference.MyXMPPServer.tld`.

What did I wrong?

**Comment by saljut7** [comment]
Solved problem using MUC-ID instead of MUC-Name.

**Comment by markstory** [comment]
Thanks for the update @saljut7!
