### ISSUE TITLE
Shortcut/alias for hubot in MUCs possible?

### ISSUE THREAD

**Issue by saljut7** [markstory/hubot-xmpp#116]
Hi,

not really an "issue" but I know from other bot engines that it is possible to "call" the bot not only by its name but with a "shortcut", example:

Instead of `MyBot ship it` it is possible to execute the same with `! ship it` so `!` is an alias for `MyBot` (and no need to type the bot name in MUCs).

I thought `HUBOT_XMPP_PM_ADD_PREFIX` enables such a shortcut but honestly I don't understand what `HUBOT_XMPP_PM_ADD_PREFIX` does. If `HUBOT_XMPP_PM_ADD_PREFIX` enables a hubot alias it doesn't work in my case (neither in MUC nor in single chat).

Thx in advance for any help
sj7

**Comment by markstory** [comment]
You should be able to use the [alias options](https://github.com/github/hubot/blob/498d65611388d2881e6ae24f74bd68a832a24211/bin/hubot#L16) of hubot to do this.

**Comment by saljut7** [comment]
Thx @markstory - works great. Just `*` does not work as alias.
