### ISSUE TITLE
Environment variable HUBOT_XMPP_PREFERRED_SASL_MECHANISM not working

### ISSUE THREAD

**Issue by wtolfday** [markstory/hubot-xmpp#118]
Setting environment variable HUBOT_XMPP_PREFERRED_SASL_MECHANISM is not working. By looking into the source code of xmpp.coffee, it looks like when creating a client, the following code has a bug:
preferredSaslMechanism: options.preferredSaslMechanism

It should be:
preferred: options.preferredSaslMechanism.

**Comment by markstory** [comment]
This was corrected already in 7396f11edd924484270fb113f7500b364b56f2dc. I had tagged the release a long time ago but forgot to publish the package to npm. It has been published now.
