### ISSUE TITLE
Pull fixes for presence from a fork

### ISSUE THREAD

**Issue by muppeth** [markstory/hubot-xmpp#125]
Whiole I was trying to find a way how to fix some issues with the xmpp module for hubot, I noticed this commit in the fork that fixes it: https://github.com/67P/hubot-xmpp/commit/acd71c36486c48a91e75e91bb58a436a2b8de03b 

Would you mind pulling it? The fork doesnt have issue's open so I couldnt as the author to create pull request, so I thought maybe you could just pull those changes. It would help a lot everyone who is using hubot on xmpp which atm is not really possible without the fix.

**Comment by markstory** [comment]
If you make a pull request here I can take care of merging and doing a release.

**Comment by muppeth** [comment]
done
