### ISSUE TITLE
Multiple xmpp bots and Environment

### ISSUE THREAD

**Issue by meaz** [markstory/hubot-xmpp#130]
Hi,

I have a prosody server. I've created multiple bots, and to do so, I've created a new folder for each instance, and then used the npx -c yo hubot ... command in each folder.

For each of these bots, I have the same xmpp environment variables. It works, I mean in the test muc, I do see myhubot1, myhubot2, etc. Could that be a problem that different bots use the same xmpp account?

thanks a lot

**Comment by sonnyp** [comment]
As long as they have different usernames it should work but I can't predict the future :)

Feel free to open an issue if you run into a problem.
