### ISSUE TITLE
Latest npm release is 0.1.12

### ISSUE THREAD

**Issue by scboucher** [markstory/hubot-xmpp#83]
The npmjs.com repository does not offer any build after 0.1.12. I am wondering if you are aware of the situation since 0.1.15 was release yesterday and unavailable from npm.

**Comment by markstory** [comment]
Whoops, I'll publish a new 0.1.16 tag.

**Comment by scboucher** [comment]
thanks

**Comment by markstory** [comment]
Not a problem, I apologize for not remembering to run `npm publish`. Other package indexes I work with pick up new tags with webhooks.
