### ISSUE TITLE
Hubot-xmpp will not connect when node version is not 0.10.9

### ISSUE THREAD

**Issue by djzager** [markstory/hubot-xmpp#99]
I have very little experience using hubot and hubot-xmpp. I am currently able to run hubot with the xmpp adapter successfully when the node version is 0.10.9:

```
[root@9df2127fd20f bot]# node -v
v0.10.9
[root@9df2127fd20f bot]# ./bin/hubot -a xmpp
[Wed Dec 16 2015 19:46:00 GMT+0000 (UTC)] DEBUG Loading adapter xmpp
[Wed Dec 16 2015 19:46:01 GMT+0000 (UTC)] INFO { username: 'someUser@domain.com',
  password: '********',
  host: '****',
  port: '5223',
  rooms: [ { jid: '****', password: false } ],
  keepaliveInterval: 30000,
  legacySSL: '1',
  preferredSaslMechanism: undefined,
  disallowTLS: undefined,
  pmAddPrefix: undefined }
[Wed Dec 16 2015 19:46:01 GMT+0000 (UTC)] INFO Hubot XMPP client online
[Wed Dec 16 2015 19:46:01 GMT+0000 (UTC)] INFO Hubot XMPP sent initial presence
```

My hubot-scripts require node 0.12.9 or higher but I am unable to run hubot with the xmpp adapter successfully:

```
[root@9df2127fd20f bot]# node -v
v0.12.9
[root@9df2127fd20f bot]# ./bin/hubot -a xmpp
[Wed Dec 16 2015 19:52:43 GMT+0000 (UTC)] DEBUG Loading adapter xmpp
[Wed Dec 16 2015 19:52:45 GMT+0000 (UTC)] INFO { username: 'someUser@domain.com',
  password: '********',
  host: '****',
  port: '5223',
  rooms: [ { jid: '****', password: false } ],
  keepaliveInterval: 30000,
  legacySSL: '1',
  preferredSaslMechanism: undefined,
  disallowTLS: undefined,
  pmAddPrefix: undefined }
[Wed Dec 16 2015 19:53:15 GMT+0000 (UTC)] DEBUG [sending ping] <iq type="get"><ping xmlns="urn:xmpp:ping"/></iq>
```
After this point I will see nothing but sending ping (with no response). I see the same behavior with node version 4.2.3 and 5.2.0.

Any help would certainly be appreciated.

**Comment by sonnyp** [comment]
@djzager can you try and past `DEBUG=* ./bin/hubot -a xmpp` ?

**Comment by djzager** [comment]
@sonnyp My apologies for missing your message.

I worked around the issue by making the hubot-scripts not require node 0.12.9. I'd like to dig deeper into this but don't think I can get to it in a timely manner, because I am 0 for 1 so far. I'll close this issue for now. Should I reopen this in the case I can past the output of `DEBUG=* ./bin/hubot -a xmpp` ?

My XMPP server/network is a corporate one which I suspect may be causing my issues and would be much more difficult to fix. But, if possible, I would much rather learn that I have been making some mistake.

Thank you for getting back to me. I'm sorry for missing the notification.

**Comment by danielechalar** [comment]
Hey,
I'm having the same issue. Here is the result of DEBUG=* ./bin/hubot -a xmpp:
$ DEBUG=* ./bin/hubot -a xmpp
Thu, 17 Nov 2016 01:49:38 GMT express:application compile etag weak
Thu, 17 Nov 2016 01:49:38 GMT express:application compile trust proxy false
Thu, 17 Nov 2016 01:49:38 GMT express:application booting in development mode
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / query
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / expressInit
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / anonymous
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / query
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / jsonParser
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / urlencodedParser
Thu, 17 Nov 2016 01:49:38 GMT connect:dispatcher use / multipart
[Wed Nov 16 2016 21:49:39 GMT-0400 (Hora estándar oeste, Sudamérica)] INFO { username: 'myUser@mygroup-slack.com',
  password: '***********',
  host: undefined,
  port: undefined,
  rooms:
   [ { jid: 'general@mygroup.slack.com',
       password: false } ],
  keepaliveInterval: 30000,
  reconnectTry: 5,
  reconnectWait: 5000,
  legacySSL: undefined,
  preferredSaslMechanism: undefined,
  disallowTLS: undefined,
  pmAddPrefix: undefined }
Thu, 17 Nov 2016 01:49:39 GMT xmpp:client:session start socket connection
Thu, 17 Nov 2016 01:49:39 GMT xmpp:connection setup socket
Thu, 17 Nov 2016 01:49:39 GMT xmpp:connection use lazy socket
Thu, 17 Nov 2016 01:49:39 GMT xmpp:connection setup stream
Thu, 17 Nov 2016 01:50:01 GMT xmpp:connection use lazy socket
Thu, 17 Nov 2016 01:50:01 GMT xmpp:connection setup stream
Thu, 17 Nov 2016 01:50:23 GMT xmpp:connection use lazy socket
Thu, 17 Nov 2016 01:50:23 GMT xmpp:connection setup stream

And that loop continues forever.

Any idea? thank you in advance

**Comment by thundergreen** [comment]
dear all i am facing exactly the same issue here .. no solution yet?
